esphome:
  name: esphome-web-59ebc4
  friendly_name: ESPHome 1
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: your_ssid
  password: your_password

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO2  # Change this to GPIO2 if you're using D2
      mode: INPUT
      inverted: true  # Set to true if you're expecting active low voltage
    name: "thirsty?"
    device_class: power # This makes it show as a power sensor in HA